### ISSUE TITLE
NameError: uninitialized constant Elasticsearch::Rails::HA::ParallelIndexer::ActiveRecord

### ISSUE THREAD

**Issue by pacuna** [18F/elasticsearch-rails-ha-gem#1]
I don't know if I'm doing this correctly. I installed the gem and ran bundle install:

```
gem 'elasticsearch-rails-ha'
```

Added the task in my rake task:

```
require 'elasticsearch/rails/tasks/import'
require 'elasticsearch/rails/ha/tasks'
```

But then when I run the task:

```
 bundle exec rake environment elasticsearch:ha:import NPROCS=4 CLASS='Article' FORCE=y
```

I'm getting

```
rake aborted!
NameError: uninitialized constant Elasticsearch::Rails::HA::ParallelIndexer::ActiveRecord
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.7/lib/elasticsearch/rails/ha/parallel_indexer.rb:52:in `run'
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.7/lib/elasticsearch/rails/ha/tasks.rb:26:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
...
```

Am I doing something wrong?

Thanks for the great work.

**Comment by pkarman** [comment]
@pacuna you're not doing anything wrong.

I've put a fix in 26449cf and just pushed 1.0.8 to rubygems. Can you verify whether that fixes your problem?

Thanks for the great bug report.

**Comment by pacuna** [comment]
@pkarman Thanks!

Now I'm getting a different error:

```
rake aborted!
NameError: uninitialized constant ActiveRecord
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.8/lib/elasticsearch/rails/ha/parallel_indexer.rb:52:in `run'
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.8/lib/elasticsearch/rails/ha/tasks.rb:26:in `block (3 levels) in <top (required)>'
Tasks: TOP => elasticsearch:ha:import
(See full trace by running task with --trace)
```

**Comment by pkarman** [comment]
hmm. that seems like your Rails app isn't loading ActiveRecord as part of that Rake task, which is a more fundamental problem.

can you try

```
bundle exec rake --trace environment elasticsearch:ha:import NPROCS=4 CLASS='Article' FORCE=y
```

and/or test that your other rake tasks are working as expected?

**Comment by pacuna** [comment]
With --trace I'm getting:

```
rake aborted!
NameError: uninitialized constant ActiveRecord
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.8/lib/elasticsearch/rails/ha/parallel_indexer.rb:52:in `run'
/var/lib/gems/2.1.0/gems/elasticsearch-rails-ha-1.0.8/lib/elasticsearch/rails/ha/tasks.rb:26:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call
```

I don't think the problem is in my app, the elasticsearch-rails gem task works fine:

```
bundle exec rake environment elasticsearch:import:model CLASS='Article'
```

**Comment by pkarman** [comment]
@pacuna I have pushed version 1.0.9 with 9f46b2a that explicitly loads ActiveRecord::Base.

I will admit I am confused if that fixes your problem, as I would have expected that loading your rails app would, by itself, load ActiveRecord::Base via the `Article` class.

Please let us know if that helps.
